name: Sanity
on:
  push:
    branches: [main]
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - name: Skipped
        if: ${{ secrets.VERCEL_TOKEN == '' }}
        run: echo "no token"
