name: Sanity
on:
  push:
    branches: [main]
concurrency:
  group: vercel-production
  cancel-in-progress: true
jobs:
  t:
    if: ${{ vars.VERCEL_DEPLOY_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
